version: 0.1

phases:
  install:
    commands:
      - echo Entering install phase...
      - echo Nothing to do now
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew run
      - echo Uploading output to s3...
      - aws s3 cp /tmp/index.html s3://letoura-dev/index.html