/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cafe.o.matic

import java.io.File

fun main(args: Array<String>) {
    val name = if (args.isNotEmpty())
        args.first()
    else
        "nobody"

    println("HELLO, $name")
    File("/tmp/index.html").writeText("$name")
}
